databases:
  - name: django-db-2
    databaseName: django_db_2
    user: django_user_2
    plan: free

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: './build.sh'
    startCommand: "python manage.py loaddata backup.json && python manage.py loaddata auth_users.json && gunicorn Django2.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-db-2
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: RENDER
        value: 'TRUE'  # Necessário para identificar o ambiente de produção no settings.py