# Generated by Django 5.2.5 on 2025-08-06 19:53

import pictures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Data de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('estoque', models.IntegerField(verbose_name='Estoque')),
                ('imagem', pictures.models.PictureField(aspect_ratios=[None, '1/1'], breakpoints={'desktop': 992, 'mobile': 576}, container_width=1200, file_types=['JPEG'], grid_columns=12, height_field='image_height', pixel_densities=[1, 2], upload_to='produto', width_field='image_width')),
                ('image_width', models.PositiveIntegerField(editable=False, null=True)),
                ('image_height', models.PositiveIntegerField(editable=False, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
