# Generated by Django 5.2.5 on 2025-08-11 22:14

import pictures.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=pictures.models.PictureField(aspect_ratios=[None, '1/1'], breakpoints={'desktop': 992, 'mobile': 576, 'thumb': 200}, container_width=1200, file_types=['PNG'], grid_columns=12, height_field='image_height', pixel_densities=[1, 2], upload_to='produtos', width_field='image_width'),
        ),
    ]
